name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
        
      - name: Restpre keras resources cache
        id: restore-keras-cache
        uses: actions/cache@v4
        with:
          path: ~/.keras
          key: keras-${{ runner.os }}-${{ hashFiles('tests/conftest.py') }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install .

      - name: Run tests
        run: pytest

      - name: Save keras resources cache
        if: steps.restore-keras-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ~/.keras
          key: keras-${{ runner.os }}-${{ hashFiles('tests/conftest.py') }}
