name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set site package path
        run: |
          python -c "import site; print(f'site_package_path={site.getsitepackages()[0]}')" >> $GITHUB_ENV
          python -c "import re,site; print(f'bin_path={re.sub(r'(.*)/bin/.*', r'\1/lib', site.getsitepackages()[0])}))" >> $GITHUB_ENV

      - name: Cache python packages
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.site_package_path }}
            ${{ env.bin_path }}
          key: ${{ runner.os }}-test-pip-${{ env.site_package_path }}-${{ hashFiles('pyproject.toml') }}
        
      - name: Cache keras resources
        id: restore-keras-cache
        uses: actions/cache@v4
        with:
          path: ~/.keras
          key: keras-${{ runner.os }}-${{ hashFiles('tests/conftest.py') }}

      - name: Install dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          pip install .

      - name: Run tests
        run: pytest
